const LEHRPLAN = {
  Mathematik: {
    1: [
      "Zahlen bis 20",
      "Einfaches Addieren",
      "Einfaches Subtrahieren",
      "Formen erkennen",
      "Mengen vergleichen",
    ],
    2: [
      "Zahlen bis 100",
      "Addition bis 100",
      "Subtraktion bis 100",
      "Einmaleins Einführung",
      "Längen messen",
    ],
    3: [
      "Zahlen bis 1000",
      "Einmaleins",
      "Multiplikation",
      "Division Einführung",
      "Flächen und Umfang",
    ],
    4: [
      "Zahlen bis 10000",
      "Schriftliche Addition",
      "Schriftliche Subtraktion",
      "Schriftliche Multiplikation",
      "Brüche Einführung",
      "Dezimalzahlen",
    ],
    5: [
      "Bruchrechnen",
      "Dezimalzahlen",
      "Prozentrechnung Einführung",
      "Fläche und Umfang",
      "Volumen",
      "Koordinatensystem",
    ],
    6: [
      "Brüche addieren und subtrahieren",
      "Prozentrechnung",
      "Verhältnisse",
      "Geometrie",
      "Statistik Einführung",
      "Negative Zahlen Einführung",
    ],
  },
  Deutsch: {
    1: [
      "Buchstaben kennen",
      "Laute hören",
      "Einfache Wörter lesen",
      "Namen schreiben",
      "Gross- und Kleinschreibung",
    ],
    2: [
      "Sätze lesen",
      "Sätze schreiben",
      "Wörter mit ch, sch, st",
      "Nomen erkennen",
      "Einfache Texte",
    ],
    3: [
      "Aufsatz Einführung",
      "Adjektive",
      "Verben",
      "Wörterbuch benutzen",
      "Texte verstehen",
    ],
    4: [
      "Aufsatz schreiben",
      "Satzglieder",
      "Zeitformen",
      "Direkte Rede",
      "Texte überarbeiten",
    ],
    5: [
      "Erörterung",
      "Grammatik vertiefen",
      "Nominativ Akkusativ Dativ",
      "Konjunktiv",
      "Literaturtexte",
    ],
    6: [
      "Argumentation",
      "Stilmittel",
      "Komplexe Grammatik",
      "Verschiedene Textarten",
      "Präsentation",
    ],
  },
  NMG: {
    1: [
      "Tiere kennen",
      "Pflanzen kennen",
      "Jahreszeiten",
      "Körper und Sinne",
      "Familie und Schule",
    ],
    2: [
      "Tiere und Lebensraum",
      "Wetter beobachten",
      "Gesunde Ernährung",
      "Berufe kennen",
      "Mein Dorf / meine Stadt",
    ],
    3: [
      "Ökosystem Wald",
      "Wasser und Kreislauf",
      "Schweizer Geschichte Einführung",
      "Energie Einführung",
      "Körper und Gesundheit",
    ],
    4: [
      "Lebensräume Schweiz",
      "Erdkunde Schweiz",
      "Römer und Mittelalter",
      "Elektrizität",
      "Ernährung und Gesundheit",
    ],
    5: [
      "Ökosysteme weltweit",
      "Kontinente",
      "Schweizer Geschichte",
      "Physik Einführung",
      "Chemie Einführung",
      "Menschenrechte",
    ],
    6: [
      "Globalisierung",
      "Klimawandel",
      "Demokratie Schweiz",
      "Wirtschaft Einführung",
      "Weltgeschichte",
      "Nachhaltigkeit",
    ],
  },
  Englisch: {
    3: [
      "Begrüssung",
      "Zahlen 1-20",
      "Farben",
      "Tiere auf Englisch",
      "Einfache Sätze",
    ],
    4: [
      "Familie",
      "Schule",
      "Essen und Trinken",
      "Simple Present",
      "Fragen stellen",
    ],
    5: [
      "Simple Past",
      "Hobbys",
      "Ferien",
      "Present Progressive",
      "Vokabeln vertiefen",
    ],
    6: [
      "Present Perfect Einführung",
      "Reisen",
      "Umwelt",
      "Texte lesen und verstehen",
      "Einfache Aufsätze",
    ],
  },
  Französisch: {
    5: [
      "Begrüssung",
      "Zahlen",
      "Farben",
      "Familie auf Französisch",
      "Einfache Sätze",
    ],
    6: [
      "Schule",
      "Essen",
      "Freizeit",
      "Présent",
      "Einfache Dialoge",
    ],
  },
  Geometrie: {
    1: [
      "Formen erkennen",
      "Muster legen",
      "Symmetrie",
      "Grundformen",
    ],
    2: [
      "Würfel Quader Kugel",
      "Messen",
      "Figuren zeichnen",
      "Umfang",
    ],
    3: [
      "Fläche berechnen",
      "Winkel kennen",
      "Koordinaten",
      "Konstruieren",
    ],
    4: [
      "Flächeninhalt",
      "Umfang berechnen",
      "Winkel messen",
      "Geometrische Körper",
    ],
    5: [
      "Volumen",
      "Oberfläche",
      "Pythagoras Einführung",
      "Massstab",
    ],
    6: [
      "Pythagoras",
      "Kreisberechnung",
      "Transformationen",
      "Koordinatensystem",
    ],
  },
};

export default LEHRPLAN;
